title: "CBS | Structural Engineering"
description: "Công cụ & kiến thức cho kỹ sư kết cấu"
theme: minima
author: Huỳnh Lê Bá Châu

markdown: kramdown
kramdown:
  math_engine: mathjax

# Thiết lập thanh menu điều hướng
header_pages:
  - cbs-tool.md
  - portfolio.md
  - huong-dan.md
  - ket-cau.md
